README.md
index.js
package.json
specs/tests/cloudscraper.js
specs/tests/errors.js

@Colecf sorry for the delay in response, i was on a freaking long vacation. But now i'm back and had opportunity to look into your PR - https://github.com/codemanki/cloudscraper/pull/5 . Looks good thanks for contributing, i've made couple improvements, added spec and made new `post` method testable. Please, take a look and let me know what you think.

[Improved] Add POST requests

---

index.js
package.json

And generalized requests.
This breaks the grunt tests, they now all timeout. I'm not sure what's wrong there, but if someone does know I'd be happy to fix it or anything else.

Add POST requests

---

index.js
specs/tests/errors.js

Sometimes body can be empty. Check to this. Fixes #9

Check for empty body

---

index.js
specs/fixtures/page_with_recaptcha.html
specs/tests/cloudscraper.js

Fixes https://github.com/codemanki/cloudscraper/issues/13
Page had recaptcha on it and cloudscraper was thinking that this is CF protection page. I've improved how cloudscraper detects recaptcha and it should not trigger any false alarms.

Improve captcha detection on CF page

---

index.js
specs/tests/errors.js

Fixes https://github.com/codemanki/cloudscraper/issues/15

Fix non returning error

---

index.js
package.json
specs/fixtures/js_challenge_09_06_2016.html
specs/tests/cloudscraper.js

Fixes https://github.com/codemanki/cloudscraper/issues/20

Fix new challenge + bump version

---

package.json

Remove tough-cookie

---

.eslintrc
README.md
index.js
package.json

Closes #70 
No code changes required as this matches the current coding style.

Add linting and code style badge

---

.gitignore
.travis.yml
README.md
package.json

Add code coverage

---

errors.js
index.js
package.json
test/common.js
test/helper.js
test/rp.js
test/test-errors.js
test/test-index.js
test/test-rp.js

* Provides a good function argument convention.
* Adds some helpful comments.
* Fixes comment line length and clarity.
* Reduces function argument complexity.
The argument convention is options first where possible, options always before response, and body always after response.

Simplify function arguments

---

index.js
test/helper.js

This fixes the issue as discussed in #73 
CI Build: https://travis-ci.org/pro-src/cloudflare-scrape/builds/501311699?utm_medium=notification&utm_source=email

Listen to error and complete events

---

test/test-index.js

Add test case for custom cookies

---

errors.js
index.js

Closes #78
This is for all parser errors.
```sh
ParserError: 
Cookie code extraction failed
at setCookieAndReload (cloudscraper/index.js:262:17)
at processRequestResponse (cloudscraper/index.js:155:5)
at Object.onceWrapper (events.js:273:13)
at Request.emit (events.js:182:13)
at Request.set (cloudscraper/test/helper.js:94:18)
at performRequest (cloudscraper/index.js:109:24)
at cloudscraper/index.js:37:16
<snipped>
```

Generate bug report message for parser errors

---

errors.js
test/test-errors.js

Closes #119 
This adds a short description for every code documented at: https://support.cloudflare.com/hc/en-us/sections/200820298-Error-Pages

Add short description to errors of type CloudflareError

---

errors.js
test/test-errors.js

Increase coverage to 100%

---

index.js
test/test-errors.js

Only call errback with the error argument

---

index.js
test/helper.js
test/test-errors.js
test/test-index.js

Improve cloudflare detection

---

index.js
test/helper.js
test/test-errors.js
test/test-index.js
test/test-rp.js

I've updated/added tests and added a global use strict statement.
Fixes #132 
Fixes #108 
Fixes #109 
Closes #134

Skip non-challenge response body types

---

README.md

Additionally corrected the name to Cloudflare

Fixed help link for error messages

---

index.js
test/test-index.js

Support the baseUrl option

---

index.js
test/test-errors.js
test/test-index.js

Validate the cloudflareTimeout option

---

index.js
test/fixtures/js_challenge_13_03_2019.html
test/test-errors.js
test/test-index.js

https://github.com/Anorov/cloudflare-scrape/issues/193

Update for new challenge

---

index.js

A new form field was added by Cloudflare. We could check for and add these form fields automatically and log a warning that we've done so to keep things working until we have a chance to update.
Fixes #148

Update for latest challenge

---

.travis.yml

This awesome bot comments on PR's with the portion of the build log that caused it to fail which is great for people who aren't familiar with CI services.
https://github.com/bluzi/travis-buddy
Plus it'll save me from having to visit travis-ci :smile:

Enable Travis Buddy [skip ci]

---

index.js
lib/email-decode.js
test/fixtures/page_with_emails.html
test/helper.js
test/test-emails.js
test/test-index.js

Fixes #41 
I've removed the method that was in #146, added a flag + additional test, and fixture.

Add option to decode emails

---

test/fixtures/js_challenge_21_03_2019.html
test/test-index.js

This adds the latest test fixture and tests to bring code coverage back to 100%

Add test for new challenge

---

package.json

This must be included in the published package.

(npm) Include lib/ directory

---

index.js

Fixes #164, partially reverts #163 (re-includes the isChallengePresent check)
This currently works without respecting the `Retry-After` header but we might have to add an option for that if more browsers add support for it.
Edit: Moved `challengesToSolve` check into the `solveChallenge` function.

Fix bug with challenge detection

---

index.js

This will help when debugging and adding challenge heuristics to the bot.

Add prepared challenge to response object

---

examples/ignore-error.js

Add example of ignoring an error

---

index.js

Mostly just improves code readability.
* Split `processRequestResponse` into two functions: `onRequestResponse` and `onCloudflareResponse`
* Update `setCookieAndReload` to match the rest of codebase, it defines `response.challenge` as expected.
* Add `response.isHTML` boolean property for code readability and to ensure `decodeEmails` only operates on responses of the correct content type.

Minor code improvements

---

index.js

Fix bug with setTimeout match length

---

lib/sandbox.js
test/test-index.js
test/test-sandbox.js

As mentioned by @Anorov https://github.com/Anorov/cloudflare-scrape/pull/234#issuecomment-491376615
There was a security issue with the prototype chain of the contextified sandbox. This PR nullifies that prototype chain.

(security) Nullify VM context's prototype chain

---

errors.js

Add CF error desc. for 1018 and 1020

---

README.md

Fixed a typo and made an adjustment to the list of contributors.

Update README.md with notes on TLS

---

docs/examples/banned.js
docs/examples/captcha-html.js
docs/examples/custom-headers-v2.js
docs/examples/custom-headers.js
docs/examples/custom-requester-v2.js
docs/examples/custom-requester.js
docs/examples/debugging.js
docs/examples/download-v2.js
docs/examples/download.js
docs/examples/ignore-error.js
docs/examples/redirects.js
docs/examples/session-persistence.js
docs/examples/solve-recaptcha-v2.js
docs/examples/solve-recaptcha.js

See #246 
* Fixed the relative import path.

Add example of session persistence

---

.eslintrc
errors.d.ts
index.d.ts
index.test-d.ts
package.json

Add typescript definitions and tests

---

.eslintrc
README.md
index.js
test/fixtures/cf_recaptcha_01_12_2019.html
test/test-captcha.js

Supersedes https://github.com/codemanki/cloudscraper/pull/292

Adjust for new recaptcha
